### ISSUE TITLE
after upgrade to 1.0.8 got this error on all sites

### ISSUE THREAD

**Issue by gviabcua** [panakour/oc-backup-plugin#13]
after upgrade to 1.0.8 got this error on all sites
"Parse error: syntax error, unexpected '?'" on line 138 of *****/www/html/plugins/panakour/backup/vendor/spatie/laravel-backup/src/BackupDestination/BackupDestination.php

**Comment by panakour** [comment]
It's because of https://github.com/spatie/laravel-backup/blob/master/src/BackupDestination/BackupDestination.php#L138

> Nullable types is new feature for php7.1 and up

 So you need at least php version 7.1

**Comment by emilianobovetti** [comment]
Maybe it's worth to update the requirements in README.md which say "this package requires PHP 7 or higher". I encountered this problem today since debian stable still provides php7.0
