### ISSUE TITLE
PHP 7.1 is required

### ISSUE THREAD

**Issue by tobias-kuendig** [panakour/oc-backup-plugin#17]
The currently shipped laravel-backup version makes use of nullable return types. 

```php
    // spatie/laravel-backup/src/BackupDestination/BackupDestination.php:138
    public function newestBackup(): ?Backup
    {
        return $this->backups()->newest();
    }
```

The minimum plugin requirements in the README and the Marketplace should be updated to require PHP 7.1

**Comment by panakour** [comment]
@tobias-kuendig updated thanks
