### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by sinyayadynya** [panakour/oc-backup-plugin#22]
Hi,
I'm using this module for the first time and I'm getting the following error when I click on 'Create backup':

`"Call to undefined method Symfony\Component\Process\Process::fromShellCommandline()" on line 186 of /Users/sahaj/Sites/tailwindui/plugins/panakour/backup/vendor/spatie/db-dumper/src/Databases/MySql.php`

I'm on mac and have mysqldump installed.

Thanks for help.

**Comment by tobias-kuendig** [comment]
Same here. It seems like this plugin ships `symfony/process` version `v5.0.7`.

I do have version `v3.4.37` installed as well. This is a required version from `laravel/framework` version `v5.5.48` which is a direct dependency of October.


```
$ composer why symfony/process    
laravel/framework        v5.5.48  requires  symfony/process (~3.3)      
```

The `fromShellCommandline` does not exist in version 3.4 of the process component.

**Comment by tobias-kuendig** [comment]
Workaround: 

Remove `plugins/panakour/vendor` directory

Create `plugins/panakour/composer.json`:

```json
{
  "name": "panakour/oc-backup-plugin",
  "type": "october-plugin",
  "description": "Backup files and database of October CMS",
  "keywords": [
    "octobercms",
    "backup"
  ],
  "license": "MIT",
  "authors": [
    {
      "name": "Panagiots Koursaris",
      "email": "panakourweb@gmail.com"
    }
  ],
  "require": {
    "php": ">=7.1",
    "spatie/laravel-backup": "~5.0",
    "spatie/flysystem-dropbox": "^1.0",
    "symfony/process": "^3.4",
    "league/flysystem-webdav": "~1.0"
  }
}
```

Run composer install.
