### ISSUE TITLE
Scoped App (App Folder) access?

### ISSUE THREAD

**Issue by zlobec** [panakour/oc-backup-plugin#28]
Plugin does not work with the new API access, right?

EDIT:
I didn't set the Permissions :D Dang... Mondays are hard! ... So here is what I found out during my enlightment session on Dropbox Console...

1. Create App
2. Set permissions (files.metadata.write, files.metadata.read, files.content.write, files.content.read)
3. Set Access token expiration to No Expiration
4. Generate access token

Works! :D

Maybe this should be written to the Readme... just to be on the safe side.

**Comment by panakour** [comment]
@zlobec  Feel free to open a PR for the readme. Thanks!
