### ISSUE TITLE
Backup folder issue

### ISSUE THREAD

**Issue by gergo85** [panakour/oc-backup-plugin#4]
When I created a backup, the file is in the "October-CMS" folder instead of "panakour-backup".
I use October build 430.

**Comment by panakour** [comment]
Did you change the name inside the config file? I have created too many backups files without this problem using October build 430.

Ps: try again with the latest version and let me know.

**Comment by gergo85** [comment]
I use the default settings and the latest version of plugin.

The plugin uses the app name (https://github.com/octobercms/october/blob/master/config/app.php#L31) as a folder name. I do not understand why this is.

**Comment by panakour** [comment]
@gergo85 what is your environment?

**Comment by gergo85** [comment]
Linux server, PHP 7.0.25

**Comment by panakour** [comment]
in a production server or local? if is local, run with docker or virtual machine (vagrant)?

**Comment by gergo85** [comment]
I run the website in a production server.

**Comment by panakour** [comment]
Are the backups created without any problem?

**Comment by gergo85** [comment]
Yes, the backup zip files are fine.

**Comment by panakour** [comment]
Unfortunately I can't reproduce this issue, I have tried with various system (ubuntu php7.0.22 - ubuntu php 7.1.5) local and remote and it works as expected.

**Comment by gergo85** [comment]
I see. I didn't find the problem.

**Comment by panakour** [comment]
Closing as it has been over a year since any activity on this occurred
