### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by zietbukuel** [panakour/oc-backup-plugin#5]
For me, it simply does not create any backup. At first it was complaining I didn't specify a MySQL port, then I added one and now it says it has created the backup, but in reality, nothing happens. Not sure how to debug this so any help is appreciated. 

I'm running PHP 7.1.12 on Apache 2.4. Permissions are ok.

Thanks.

**Comment by panakour** [comment]
Is mysqldump installed on your system and [ZIP module](http://php.net/manual/en/book.zip.php) enabled ?

**Comment by zietbukuel** [comment]
Yes, I have both.

```
$ php -m | grep zip
zip
```

```
$ mysqldump -V
mysqldump  Ver 10.16 Distrib 10.2.11-MariaDB, for osx10.13 (x86_64)
```

**Comment by panakour** [comment]
Did you have any error in the log file?

**Comment by zietbukuel** [comment]
Absolutely nothing.

**Comment by panakour** [comment]
try to run the artisan command: `php artisan backup:run --disable-notifications -vvv` and let me know the result

**Comment by zietbukuel** [comment]
Ok, this seems to be working. This is the output:

```
Starting backup...
Dumping database mydb...
Gzipping mydb...
Determining files to backup...
Zipping 13903 files...
Created zip containing 13903 files. Size is 27.22 MB
Copying zip to disk named local...
Successfully copied zip to disk named local.
Backup completed!
```

However, when I try to download the backup from the backend I get a 404.

**Comment by panakour** [comment]
so your issue is related with this one #4

**Comment by zietbukuel** [comment]
I think mine is different because my backup was created inside `storage/app/panakour-backup/` and not some other folder.

Also, the link to download the archive is correct, but somehow I'm getting a 404.

**Comment by panakour** [comment]
Then the problem is related to your server.

**Comment by zietbukuel** [comment]
How so? Could you explain what's wrong with it so I can try to find a solution maybe? Thanks.

**Comment by panakour** [comment]
Maybe something with your user privilege.
You should give access to your web server (apache) to storage directory with the follow commands
```
sudo chgrp -R www-data storage
sudo chmod -R ug+rwx storage
```
Try the above from the root of your project

**Comment by zietbukuel** [comment]
Permissions are ok, ownership too. I guess this is just something not working on my local computer, it's ok. The good thing is that it works perfectly fine in my prod server.
