### ISSUE TITLE
Dropbox support issue

### ISSUE THREAD

**Issue by gergo85** [panakour/oc-backup-plugin#6]
I updated the plugin to 1.0.4 from 1.0.3 and I got the following error message:
![error](https://user-images.githubusercontent.com/2959112/34662716-ebb6db42-f452-11e7-8465-c52db4f61572.jpg)

**Comment by panakour** [comment]
@gergo85 Now with version 1.0.5 it'll be ok. Thanks

**Comment by gergo85** [comment]
It works again, thanks.
