### ISSUE TITLE
Backup error

### ISSUE THREAD

**Issue by devillom** [panakour/oc-backup-plugin#7]
On last update and click App backup and db backup

**Comment by panakour** [comment]
@devillom This is not my plugin. Are you sure that your are using this one http://octobercms.com/plugin/panakour-backup

**Comment by devillom** [comment]
ops! sorry)

**Comment by devillom** [comment]
@panakour But, similar error in your plugin.
maybee error in my version of php
"Type error: Argument 1 passed to Spatie\Backup\Tasks\Backup\BackupJobFactory::createDbDumpers() must be of the type array, null given, called in /home/c/cc07860/builders-steps.ru/public_html/plugins/panakour/backup/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php on line 14" on line 25 of /home/c/cc07860/builders-steps.ru/public_html/plugins/panakour/backup/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php
