### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by dathwa** [panakour/oc-backup-plugin#8]
Hi. Running ocms v433, PHP 7.2.1. any ideas?

Works fine online. However, I get a page not found error when i try to download from backend. e.g. https://www.example.com/storage/app/panakour-backup/xxx2018-01-30-13-31-23.zip

[error.txt](https://github.com/panakour/oc-backup-plugin/files/1677843/error.txt)

**Comment by damsfx** [comment]
Hi,
Temporary workaround here [/panakour/oc-backup-plugin/issues/9](https://github.com/panakour/oc-backup-plugin/issues/9)

**Comment by panakour** [comment]
with the new version it should be ok. I will close this issue now and feel free to open new one if the problem exist.
